### ISSUE TITLE
Wrong tag in the example

### ISSUE THREAD

**Issue by sjmikler** [blinemedical/setup-gstreamer#185]
Your example doesn't work for me:
```
- name: Setup GStreamer
  id:   setup_gstreamer
  uses: blinemedical/setup-gstreamer@1.0
  with:
    version: '1.19.90'
    arch: 'x86'
- run: |
    echo $env:GSTREAMER_1_0_ROOT_MSVC_X86
```

The available tags are: v1, v1.0.0, etc.

So I had to change
```
  uses: blinemedical/setup-gstreamer@1.0
```

to

```
  uses: blinemedical/setup-gstreamer@v1.4.0
```
